### ISSUE TITLE
Could not find com.veryfi.lens:veryfi-lens-sdk:1.7.1.12.

### ISSUE THREAD

**Issue by annexcloudkrishna** [veryfi/veryfi-lens-flutter-demo#43]
I am getting error, when I am cloning repository, from https://github.com/Annex-Cloud/NGRS

![image](https://github.com/veryfi/veryfi-lens-flutter-demo/assets/145128513/8b145b4d-ac94-438e-a517-7655583005a1)

**Comment by seramirezdev** [comment]
Did you add your MAVEN credentials to the system environment?
