### ISSUE TITLE
Flutter build issue

### ISSUE THREAD

**Issue by paccerpro** [veryfi/veryfi-lens-flutter-demo#67]
Swift Compiler Error (Xcode): Compiling for iOS 12.0, but module 'AWSCore' has a minimum deployment target of iOS 14.0: /Users/aaanand/airmiles_flutter_workspace/apps/airmiles_flutter/build/ios/Debug-iphonesimulator/AWSCore/AWSCore.framework/Modules/AWSCore.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

Swift Compiler Error (Xcode): Failed to build module 'VeryfiLens'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)', while this compiler is 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)'). Please select a toolchain which matches the SDK.
/Users/aaanand/.pub-cache/git/flutter-plugin-veryfi-lens-fa34a6f1a860838ab5f96702fce1440de4f0a563/ios/Classes/SwiftVeryfiPlugin.swift:9:7

**Comment by alejouribesanchez** [comment]
Could you try the last version https://github.com/veryfi/veryfi-lens-flutter-demo/releases/tag/v1.5.40 ? it supports the last version of Xcode maybe it was related with that

**Comment by alejouribesanchez** [comment]
Same issue face 1 of our customers in their own project and they fixed the problem deleting the iOS Folder and running `flutter create`
